-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 07:29:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema casino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casino` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `casino` ;

-- -----------------------------------------------------
-- Table `casino`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`games` ;

CREATE TABLE IF NOT EXISTS `casino`.`games` (
  `id_games` INT(11) NOT NULL,
  `id_player` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_games`),
  UNIQUE INDEX `id_games_UNIQUE` (`id_games` ASC) VISIBLE,
  INDEX `id_player_idx` (`id_player` ASC) VISIBLE,
  CONSTRAINT `id_keno`
    FOREIGN KEY (`id_games`)
    REFERENCES `casino`.`keno` (`id_keno`),
  CONSTRAINT `id_lotto`
    FOREIGN KEY (`id_games`)
    REFERENCES `casino`.`lotto` (`id_lotto`),
  CONSTRAINT `id_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `casino`.`player` (`favorite_game`),
  CONSTRAINT `id_poker`
    FOREIGN KEY (`id_games`)
    REFERENCES `casino`.`poker` (`id_poker`),
  CONSTRAINT `id_roulette`
    FOREIGN KEY (`id_games`)
    REFERENCES `casino`.`roulette` (`id_roulette`),
  CONSTRAINT `id_slots`
    FOREIGN KEY (`id_games`)
    REFERENCES `casino`.`slots` (`id_slots`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`keno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`keno` ;

CREATE TABLE IF NOT EXISTS `casino`.`keno` (
  `id_keno` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_keno`),
  UNIQUE INDEX `id_keno_UNIQUE` (`id_keno` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`lotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`lotto` ;

CREATE TABLE IF NOT EXISTS `casino`.`lotto` (
  `id_lotto` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lotto`),
  UNIQUE INDEX `id_lotto_UNIQUE` (`id_lotto` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`player` ;

CREATE TABLE IF NOT EXISTS `casino`.`player` (
  `id_player` INT(11) NOT NULL,
  `favorite_game` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_player`),
  UNIQUE INDEX `idplayer_UNIQUE` (`id_player` ASC) VISIBLE,
  UNIQUE INDEX `favorite_game_UNIQUE` (`favorite_game` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`poker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`poker` ;

CREATE TABLE IF NOT EXISTS `casino`.`poker` (
  `id_poker` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_poker`),
  UNIQUE INDEX `id_poker_UNIQUE` (`id_poker` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`roulette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`roulette` ;

CREATE TABLE IF NOT EXISTS `casino`.`roulette` (
  `id_roulette` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_roulette`),
  UNIQUE INDEX `id_roulette_UNIQUE` (`id_roulette` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `casino`.`slots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casino`.`slots` ;

CREATE TABLE IF NOT EXISTS `casino`.`slots` (
  `id_slots` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_slots`),
  UNIQUE INDEX `id_slots_UNIQUE` (`id_slots` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
